### ISSUE TITLE
Travis build failing

### ISSUE THREAD

**Issue by bartnijssen** [UW-Hydro/VIC#669]
```
Traceback (most recent call last):
  File "./tests/run_tests.py", line 17, in <module>
    from tonic.io import read_config, read_configobj
  File "/home/travis/miniconda/envs/vic_test_env/lib/python3.5/site-packages/tonic/io.py", line 5, in <module>
    from netCDF4 import Dataset
  File "/home/travis/miniconda/envs/vic_test_env/lib/python3.5/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: libmfhdf.so.0: cannot open shared object file: No such file or directory
```

**Comment by bartnijssen** [comment]
Closed per #670
